#!/usr/bin/env bash

if
  [[ -s "/home/runner/ethereum-org-website/.bundle/ruby/3.2.0/environment" ]]
then
  source "/home/runner/ethereum-org-website/.bundle/ruby/3.2.0/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/runner/ethereum-org-website/.bundle/ruby/3.2.0/environment'" >&2
  exit 1
fi
