{pkgs}: {
  deps = [
    pkgs.apk-tools
    pkgs.haskellPackages.Raincat
    pkgs.perl536Packages.RSSParserLite
    pkgs.perl536Packages.RegexpTrie
    pkgs.perl538Packages.RegexpAssemble
    pkgs.perl538Packages.RSSParserLite
    pkgs.rstudioWrapper
    pkgs.perl536Packages.RESTClient
    pkgs.perlPackages.RTClientREST
    pkgs.rhodium-libre
    pkgs.perl538Packages.Readonly
    pkgs.realesrgan-ncnn-vulkan
    pkgs.dotnetPackages.RestSharp
    pkgs.raxml
    pkgs.perl538Packages.RoleHasMessage
    pkgs.perl536Packages.RoleHooks
    pkgs.haskellPackages.RMP
    pkgs.rstudioServerWrapper
    pkgs.perl536Packages.ReturnValue
    pkgs.perlPackages.RoleHooks
    pkgs.raxml-mpi
    pkgs.haskellPackages.RandomDotOrg
    pkgs.perl536Packages.RegexpGrammars
    pkgs.perl536Packages.RegexpCommon
    pkgs.haskellPackages.RESTng
    pkgs.haskellPackages.Redmine
    pkgs.haskellPackages.RoyalMonad
    pkgs.runescape
    pkgs.perl538Packages.RPCEPCService
    pkgs.rWrapper
    pkgs.R
    pkgs.perl538Packages.NetLDAPServerTest
    pkgs.gnome.networkmanager-l2tp
    pkgs.haskellPackages.NaCl
    pkgs.perlPackages.NetCIDR
    pkgs.perl538Packages.NetIP
    pkgs.dotnetPackages.NUnitRunners
    pkgs.perlPackages.NetAsyncHTTPServer
    pkgs.perl536Packages.NetFrameLayerIPv6
    pkgs.perlPackages.NetOAuth
    pkgs.perl536Packages.NetAMQP
    pkgs.perlPackages.NumberPhone
    pkgs.perl538Packages.NetIPXS
    pkgs.perl538Packages.NetSSH
    pkgs.perlPackages.NetServer
    pkgs.perl538Packages.NetIPLite
    pkgs.perlPackages.NetFastCGI
    pkgs.perlPackages.NetSSLeay
    pkgs.haskellPackages.NineP
    pkgs.haskellPackages.NearContextAlgebra
    pkgs.dotnetPackages.Nuget
    pkgs.perlPackages.NetAmazonEC2
    pkgs.perl536Packages.NumberMisc
    pkgs.perl538Packages.NetFrameLayerIPv6
    pkgs.perl538Packages.NetDNSNative
    pkgs.haskellPackages.NXTDSL
    pkgs.perl538Packages.NetAsyncWebSocket
    pkgs.perl538Packages.NetAddrIP
    pkgs.haskellPackages.NoSlow
    pkgs.haskellPackages.Naperian
    pkgs.perlPackages.NetLDAPServerTest
    pkgs.perlPackages.AppMusicChordPro
    pkgs.perl538Packages.AlgorithmBackoff
    pkgs.perl536Packages.ArchiveLibarchivePeek
    pkgs.perl536Packages.AnyEventRabbitMQ
    pkgs.perl538Packages.AuthenSimplePasswd
    pkgs.perlPackages.AlienTidyp
    pkgs.perl538Packages.AstroFITSHeader
    pkgs.ants
    pkgs.perl538Packages.AnyEventI3
    pkgs.perl538Packages.AlienSDL
    pkgs.anttweakbar
    pkgs.perlPackages.AnyEventBDB
    pkgs.haskellPackages.Ansi2Html
    pkgs.perl538Packages.ApacheTest
    pkgs.perlPackages.AppPackager
    pkgs.perl538Packages.AppCLI
    pkgs.perlPackages.AlgorithmLCSS
    pkgs.haskellPackages.AC-Vector
    pkgs.perl536Packages.ArrayRefElem
    pkgs.haskellPackages.AC-Vector-Fancy
    pkgs.haskellPackages.AMI
    pkgs.perlPackages.ArchiveTarWrapper
    pkgs.perlPackages.Applify
    pkgs.perl536Packages.AuthenSCRAM
    pkgs.perlPackages.AudioCuefileParser
    pkgs.anytype
    pkgs.perl536Packages.AnyEventCacheDNS
    pkgs.perl538Packages.AppMusicChordPro
    pkgs.perlPackages.AlgorithmBackoff
    pkgs.perlPackages.AltCryptRSABigInt
    pkgs.rPackages.pd_drogene_1_1_st
    pkgs.rubyPackages_3_1.tty-color
    pkgs.ocamlPackages.ocp-ocamlres
    pkgs.rubyPackages.http-cookie
    pkgs.rubyPackages_3_1.paru
    pkgs.rPackages.pd_equgene_1_0_st
    pkgs.rubyPackages.octokit
    pkgs.rubyPackages_3_1.cocoapods-downloader
    pkgs.rPackages.MafDb_gnomAD_r2_1_hs37d5
    pkgs.rubyPackages.mab
    pkgs.rubyPackages.byebug
    pkgs.rubyPackages_3_1.data_objects
    pkgs.rubyPackages_3_1.thrift
    pkgs.rubyPackages.pwntools
    pkgs.rubyPackages_3_1.indieweb-endpoints
    pkgs.rubyPackages_3_1.psych
    pkgs.rubyPackages_3_1.camping
    pkgs.rubyPackages_3_1.jekyll-mentions
    pkgs.rubyPackages_3_1.rmagick
    pkgs.rubyPackages.colorator
    pkgs.ocamlPackages.inifiles
    pkgs.rubyPackages.rb-readline
    pkgs.rPackages.pd_felgene_1_1_st
    pkgs._1password-gui-beta
    pkgs._1password
    pkgs.agdaPackages._1lab
    pkgs._1password-gui
    pkgs.sbclPackages._1am
    pkgs._1oom
    pkgs.python312Packages.overpy
    pkgs.haskellPackages.flow-er
    pkgs.img2pdf
    pkgs.rPackages.robfilter
    pkgs.python311Packages.rfc3987
    pkgs.rubyPackages_3_2.rb-inotify
    pkgs.haskellPackages.bytestring-arbitrary
    pkgs.rPackages.firebase
    pkgs.python311Packages.robotframework-excellib
    pkgs.emacsPackages.ansible-vault
    pkgs.python311Packages.pytest-forked
    pkgs.rPackages.bbsBayes
    pkgs.gnomeExtensions.kimpanel
    pkgs.perlPackages.TestCPANMeta
    pkgs.linuxPackages_xanmod_latest.nvidia_x11_vulkan_beta
    pkgs.emacsPackages.gnuplot-mode
    pkgs.haskellPackages.pipes-attoparsec
    pkgs.rPackages.stemmatology
    pkgs.rPackages.Density_T_HoldOut
    pkgs.python312Packages.pytestCheckHook
    pkgs.rPackages.MEDITS
    pkgs.python312Packages.xstatic-font-awesome
    pkgs.rPackages.verhoeff
    pkgs.rPackages.MadanTextNetwork
    pkgs.haskellPackages.options-time
    pkgs.perlPackages.HTMLFormatExternal
    pkgs.haskellPackages.smallstring
    pkgs.python311Packages.mkdocs
    pkgs.haskellPackages.SMTPClient
    pkgs.rPackages.camcorder
    pkgs.postgresql
  ];
}
