{pkgs}: {
  deps = [
    pkgs.rPackages.pd_drogene_1_1_st
    pkgs.rubyPackages_3_1.tty-color
    pkgs.ocamlPackages.ocp-ocamlres
    pkgs.rubyPackages.http-cookie
    pkgs.rubyPackages_3_1.paru
    pkgs.rPackages.pd_equgene_1_0_st
    pkgs.rubyPackages.octokit
    pkgs.rubyPackages_3_1.cocoapods-downloader
    pkgs.rPackages.MafDb_gnomAD_r2_1_hs37d5
    pkgs.rubyPackages.mab
    pkgs.rubyPackages.byebug
    pkgs.rubyPackages_3_1.data_objects
    pkgs.rubyPackages_3_1.thrift
    pkgs.rubyPackages.pwntools
    pkgs.rubyPackages_3_1.indieweb-endpoints
    pkgs.rubyPackages_3_1.psych
    pkgs.rubyPackages_3_1.camping
    pkgs.rubyPackages_3_1.jekyll-mentions
    pkgs.rubyPackages_3_1.rmagick
    pkgs.rubyPackages.colorator
    pkgs.ocamlPackages.inifiles
    pkgs.rubyPackages.rb-readline
    pkgs.rPackages.pd_felgene_1_1_st
    pkgs._1password-gui-beta
    pkgs._1password
    pkgs.agdaPackages._1lab
    pkgs._1password-gui
    pkgs.sbclPackages._1am
    pkgs._1oom
    pkgs.python312Packages.overpy
    pkgs.haskellPackages.flow-er
    pkgs.img2pdf
    pkgs.rPackages.robfilter
    pkgs.python311Packages.rfc3987
    pkgs.rubyPackages_3_2.rb-inotify
    pkgs.haskellPackages.bytestring-arbitrary
    pkgs.rPackages.firebase
    pkgs.python311Packages.robotframework-excellib
    pkgs.emacsPackages.ansible-vault
    pkgs.python311Packages.pytest-forked
    pkgs.rPackages.bbsBayes
    pkgs.gnomeExtensions.kimpanel
    pkgs.perlPackages.TestCPANMeta
    pkgs.linuxPackages_xanmod_latest.nvidia_x11_vulkan_beta
    pkgs.emacsPackages.gnuplot-mode
    pkgs.haskellPackages.pipes-attoparsec
    pkgs.rPackages.stemmatology
    pkgs.rPackages.Density_T_HoldOut
    pkgs.python312Packages.pytestCheckHook
    pkgs.rPackages.MEDITS
    pkgs.python312Packages.xstatic-font-awesome
    pkgs.rPackages.verhoeff
    pkgs.rPackages.MadanTextNetwork
    pkgs.haskellPackages.options-time
    pkgs.perlPackages.HTMLFormatExternal
    pkgs.haskellPackages.smallstring
    pkgs.python311Packages.mkdocs
    pkgs.haskellPackages.SMTPClient
    pkgs.rPackages.camcorder
    pkgs.postgresql
  ];
}
